### ISSUE TITLE
For exer #5, the no need to copy istio-0.6.0/bin/istioctl

### ISSUE THREAD

**Issue by nilesh32** [szihai/istio-workshop#11]
For the #5, there is no need to copy **istio-0.6.0/bin/istioctl** to **/usr/local/bin** and then asking users to enter the sudo password. In fact, it's risky. If a user mistype the sudo password first time, it doesn't ask for the password again if you try to run **sudo cp istio-0.6.0/bin/istioctl /usr/local/bin** again. It just keep throwing path unavailable method.

I tried our original method at https://github.com/szihai/istio-workshop/blob/think/exercise-5/README.md. It works fine. Please test on your side as well to make sure.

**Comment by szihai** [comment]
changed.
